import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>NFT App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="http://localhost:3000">Health Data NFT!</a>
        </h1>

        <div className={styles.grid}>
          <a href="/createNFT" className={styles.card}>
            <p>Create NFT</p>
          </a>
          <a href="/callapi" className={styles.card}>
            <p>update NFT</p>
          </a>
        </div>
      </main>
    </div>
  );
}
